#!/bin/bash

homedir=$(ls -d ~)
file="${homedir}/.countdown"
if [ ! -e $file ]; then
	touch $file
elif [ ! -f $file ]; then
	echo "Invalid countdown file: $file"
	exit 1
fi

now=$(date +%s)
usage="\
Usage: $(basename $0)                       #get time until destination
       $(basename $0) [--add|-a] time name  #assign time to the name
       $(basename $0) [--reset|-r]          #reset trackers
       See man date(1) for time add/reset format."

if [ $# -gt 0 ]; then
	case $1 in
		--add|-a)
			if [ $# -ne 3 ]; then
				echo "$usage"
				exit 1
			fi
			echo -n "$3:"$(date -d "$2" +%s)"::" >> $file
			exit
			;;
		--reset|-r)
			echo -n "" > $file
			exit
			;;
		--help|-h)
			echo "$usage"
			exit
			;;
		*)
			echo "$usage"
			exit 1
			;;
	esac
fi

records=$(cat $file)
numrecords=$(cat $file | grep '::' | wc -l)

while [ $numrecords -gt 0 ]; do
	destfull=$(echo $records | awk -F:: '{print $1}')
	destname=$(echo $destfull | awk -F: '{print $1}')
	dest=$(echo $destfull | awk -F: '{print $2}')
	
	interval=$(( $dest - $now ))
	seconds=$(( $interval % 60 ))
	
	interval=$(( $interval - $seconds ))
	minutes=$(( $interval % 3600 / 60 ))
	
	interval=$(( $interval - $minutes ))
	hours=$(( $interval % 86400 / 3600 ))
	
	interval=$(( $interval - $hours ))
	days=$(( $interval % 604800 / 86400 ))
	
	interval=$(( $interval - $hours ))
	weeks=$(( $interval / 604800 ))
	
	echo $weeks" weeks, "$days" days, "$hours" hours, "$minutes" minutes, "$seconds" seconds until "$destname"."
	
	records="${records#$destfull"::"}"
	numrecords=$(( $numrecords - 1 ))
done
